on:
 push:
    branches:
      - main
    paths-include:
      - ms-roles-api/*
      
 workflow_dispatch:                
    inputs:
      reason:
        description: "Why run this manually?"
        required: false
        default: "manual run"
jobs:
    build_and_deploy_job:
        runs-on: ubuntu-latest
        name: Build and push to ACR and promoto to ACA
        steps:
        - name: Azure login
          uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}