name: UI Tests

on:
  pull_request:
    branches: [ main ]
    types: [ready_for_review]
  workflow_dispatch:                
    inputs:
      reason:
        description: "Why run this manually?"
        required: false
        default: "manual run"

permissions: # Required when using Microsoft Entra ID to authenticate
  id-token: write
  contents: read

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    name: Run Playwright UI Tests
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20.19.5'
      #     cache: 'npm'

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build

      - name: Run Playwright tests with Azure service
        run: npx playwright test -c playwright.service.config.ts --workers=15
        env:
          PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL }}

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
